// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDL8P7ovbVGD6gsxyzc8wyUvYk4rIJHEZ8',
    appId: '1:429996520936:web:cbfe3e363119fc3f01605d',
    messagingSenderId: '429996520936',
    projectId: 'project-e8970',
    authDomain: 'project-e8970.firebaseapp.com',
    storageBucket: 'project-e8970.firebasestorage.app',
    measurementId: 'G-0YH0023VCN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCT0P1ORCuaUHAnMrVxHSeJxoCezU9-qek',
    appId: '1:429996520936:android:4c77315219e0722001605d',
    messagingSenderId: '429996520936',
    projectId: 'project-e8970',
    storageBucket: 'project-e8970.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwJ0Ig0uHzaL_zLZgaHU44gYkxmz8GraE',
    appId: '1:429996520936:ios:3499ba6dd4509d0701605d',
    messagingSenderId: '429996520936',
    projectId: 'project-e8970',
    storageBucket: 'project-e8970.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwJ0Ig0uHzaL_zLZgaHU44gYkxmz8GraE',
    appId: '1:429996520936:ios:3499ba6dd4509d0701605d',
    messagingSenderId: '429996520936',
    projectId: 'project-e8970',
    storageBucket: 'project-e8970.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDL8P7ovbVGD6gsxyzc8wyUvYk4rIJHEZ8',
    appId: '1:429996520936:web:4247661bea72824701605d',
    messagingSenderId: '429996520936',
    projectId: 'project-e8970',
    authDomain: 'project-e8970.firebaseapp.com',
    storageBucket: 'project-e8970.firebasestorage.app',
    measurementId: 'G-5T6GC55VK6',
  );
}
